<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CHALAMA" ignored="6" name="LoginTest" tests="6" failures="2" timestamp="2020-11-19T12:06:39 IST" time="56.218" errors="0">
  <testcase name="@AfterMethod tearDown" time="0.001" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:114)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="com.qa.Base.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.TestBase.tearDown(TestBase.java:114)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="ManualLogin" time="20.766" classname="com.qa.TestCases.ManualLoginTest"/>
  <testcase name="LoginWithBlank" time="3.556" classname="com.qa.TestCases.ManualLoginTest"/>
  <testcase name="LoginWithEmailAndBlankPassword" time="0.242" classname="com.qa.TestCases.ManualLoginTest"/>
  <testcase name="LoginWithBlankEmailAndPassword" time="6.62" classname="com.qa.TestCases.ManualLoginTest"/>
  <testcase name="FacebookSocialLogin" time="0.002" classname="com.qa.TestCases.FacebookLoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.TestCases.FacebookLoginTest.FacebookSocialLogin(FacebookLoginTest.java:14)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- FacebookSocialLogin -->
  <testcase name="GoogleSocialLogin" time="0.004" classname="com.qa.TestCases.GoogleLoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.TestCases.GoogleLoginTest.GoogleSocialLogin(GoogleLoginTest.java:14)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- GoogleSocialLogin -->
  <testcase name="@BeforeTest initalization" time="0.0" classname="com.qa.Base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest initalization -->
  <testcase name="@BeforeTest initalization" time="0.0" classname="com.qa.Base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest initalization -->
  <testcase name="@BeforeSuite setExtent" time="0.0" classname="com.qa.Base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtent -->
  <testcase name="@BeforeSuite setExtent" time="0.0" classname="com.qa.Base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtent -->
  <testcase name="@AfterTest endReport" time="0.0" classname="com.qa.Base.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest endReport -->
  <testcase name="@AfterTest endReport" time="0.0" classname="com.qa.Base.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest endReport -->
</testsuite> <!-- LoginTest -->
