<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CHALAMA" ignored="0" name="ManualLoginTest" tests="4" failures="1" timestamp="2020-11-19T11:52:00 IST" time="16.47" errors="0">
  <testcase name="ManualLogin" time="0.006" classname="com.qa.TestCases.ManualLoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.TestCases.ManualLoginTest.ManualLogin(ManualLoginTest.java:40)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- ManualLogin -->
  <testcase name="LoginWithBlank" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithBlank -->
  <testcase name="LoginWithEmailAndBlankPassword" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithEmailAndBlankPassword -->
  <testcase name="LoginWithBlankEmailAndPassword" time="0.0" classname="com.qa.TestCases.ManualLoginTest">
    <skipped/>
  </testcase> <!-- LoginWithBlankEmailAndPassword -->
</testsuite> <!-- ManualLoginTest -->
